apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: mrudulaa94/billing_system_frontend
        ports:
        - containerPort: 9000
        resources:  # Specify resource requests and limits
          requests:
            cpu: "100m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1524Mi"
